name: CD - Deploy to WSL Server

on:
  workflow_run:
    workflows: ["Build & Push Docker Image"]
    types:
      - completed
    branches:
      - main

env:
  IMAGE_NAME: linked

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Get Image Tag
        id: get_tag
        run: |
          SHORT_SHA=$(echo "${{ github.event.workflow_run.head_sha }}" | cut -c1-7)
          echo "IMAGE_TAG=${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Deploy
        env:
          IMAGE_FULL_URL: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.get_tag.outputs.IMAGE_TAG }}
        run: |
          cd ~/mzc-project01
          
          sed -i "s/^IMAGE_TAG=.*/IMAGE_TAG=${{ steps.get_tag.outputs.IMAGE_TAG }}/" .env
          
          docker pull $IMAGE_FULL_URL
          docker compose up -d
          docker image prune -af
          
          echo "Deployed: $IMAGE_FULL_URL"
